spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true


  config:
    import: application-secret.yml

app:
  jwt:
    secret: gaasldgjhasdflgjhlkwjlkdjalsdhjlksdgfhajlsd